[default]
depends = ["powershell", "nvim", "code", "git", "fd"]

[powershell.files]
".profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
".config/powershell" = "~/.config/powershell"
