shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-autosuggestions.hooks]
post = "bindkey '^ ' autosuggest-accept"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.local-defer]
local = "~/.config/zsh/defer"
use = ["*.zsh"]
apply = ["defer"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
