shell = "zsh"

[plugins]

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-z]
github = "agkozak/zsh-z"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
