[helpers]

[default]
depends = ["zsh", "nvim", "code", "git", "fd"]

# Shell
[zsh]
depends = ["sheldon", "starship"]

[zsh.files]
".config/zsh" = "~/.config/zsh"
".zshenv" = "~/.zshenv"

[powershell]
depends = ["starship"]

[powershell.files]
".profile.ps1" = "~/.config/powershell/Microsoft.PowerShell_profile.ps1"
".config/powershell" = "~/.config/powershell"

[sheldon.files]
".config/sheldon" = { target = "~/.config/sheldon", type = "symbolic" }

[starship.files]
".config/starship" = "~/.config/starship"

# Editor
[nvim.files]
".config/nvim" = "~/.config/nvim"

[code.files]
".config/Code" = "~/.config/Code"

# Utility
[git.files]
".config/git" = "~/.config/git"

[fd.files]
".config/fd" = "~/.config/fd"
