[helpers]

[default]
depends = []

[default.files]
".config/Code" = "~/.config/Code"
".config/git" = "~/.config/git"
".config/nvim" = "~/.config/nvim"
# ".config/powershell" = "~/.config/powershell"
".config/sheldon" = { target = "~/.config/sheldon", type = "symbolic" }
".config/starship" = "~/.config/starship"
".config/zsh" = "~/.config/zsh"
".config/fd" = "~/.config/fd"
".zshenv" = "~/.zshenv"

[default.variables]
